/**
 * DocGen Ingest — Ingests a DOCUMENTATION.md into a new or existing memory profile.
 * The sky blue button. Creates structured nodes from the generated documentation.
 */
var DocGenIngest = (function () {

  function init() {
    document.getElementById('btn-docgen-ingest').addEventListener('click', startIngest);
  }

  async function startIngest() {
    // Step 1: Pick the DOCUMENTATION.md file
    var fileInput = document.createElement('input');
    fileInput.type = 'file';
    fileInput.accept = '.md';

    fileInput.addEventListener('change', async function () {
      if (!fileInput.files || fileInput.files.length === 0) return;

      var file = fileInput.files[0];
      var text = await file.text();

      if (text.length < 100 || !text.includes('Generated by Liminal Memory DocGen')) {
        Chat.renderSystem('✗ This doesn\'t look like a DocGen-generated document.');
        return;
      }

      // Step 2: Ask user — new profile or current?
      var choice = confirm(
        'Ingest "' + file.name + '" as structured memory nodes.\n\n' +
        'OK = Create a new memory profile (recommended)\n' +
        'Cancel = Add to current memory'
      );

      var profileName = null;
      if (choice) {
        // New profile
        var suggested = file.name.replace(/DOCUMENTATION\.?/gi, '').replace(/\.md$/i, '').replace(/[^a-z0-9]/gi, '-').replace(/^-|-$/g, '') || 'docgen';
        profileName = prompt('New profile name:', suggested);
        if (!profileName) return;
        profileName = profileName.toLowerCase().replace(/[^a-z0-9\-]/g, '-').replace(/^-|-$/g, '');

        // Create the profile
        var createRes = await fetch('/api/profiles/create', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ name: profileName })
        });
        var createData = await createRes.json();
        if (!createData.success) {
          Chat.renderSystem('✗ ' + createData.error);
          return;
        }

        // Switch to it
        await fetch('/api/profiles/switch', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ name: profileName })
        });

        Chat.renderSystem('✓ Created and switched to profile: "' + profileName + '"');
      }

      // Step 3: Parse the documentation into structured nodes
      Chat.renderSystem('⬇ Parsing documentation into nodes...');
      Topbar.setStatus('active', 'DOCGEN INGEST');

      var nodes = parseDocGenMarkdown(text);
      Chat.renderSystem('⬇ Parsed ' + nodes.length + ' nodes. Ingesting...');

      // Step 4: Store nodes in memory
      var memory = window._liminalMemory;
      if (profileName) {
        // If new profile, re-init memory (reload page after)
        // For now store via API since memory instance is still old profile
        // Just save the nodes as a state file directly
        var state = buildStateFromNodes(nodes);
        await fetch('/api/state/save', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(state, null, 2)
        });
        Chat.renderSystem('✓ Ingested ' + nodes.length + ' nodes into profile "' + profileName + '". Reloading...');
        setTimeout(function () { window.location.reload(); }, 1500);
      } else {
        // Add to current memory
        var count = 0;
        for (var i = 0; i < nodes.length; i++) {
          var n = nodes[i];
          var node = memory.chain.append('system', n.content);
          memory.bm25.add(node);
          count++;
        }
        if (window._refreshStats) window._refreshStats();
        Chat.renderSystem('✓ Ingested ' + count + ' nodes into current memory.');
        // Auto-save
        try {
          await fetch('/api/state/save', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(memory.export(), null, 2)
          });
        } catch (e) { /* non-critical */ }
      }

      Topbar.setStatus('idle', 'IDLE');
    });

    fileInput.click();
  }

  /**
   * Parse a DocGen DOCUMENTATION.md into structured nodes.
   * Creates three tiers:
   * 1. One overview node (project summary)
   * 2. One file summary node per file (path + description + exports + deps)
   * 3. One function node per function (path + signature + explanation + source code)
   */
  function parseDocGenMarkdown(text) {
    var nodes = [];
    var lines = text.split('\n');

    // Split into major sections by ## headings
    var sections = [];
    var currentLines = [];
    var currentHeading = '';

    for (var i = 0; i < lines.length; i++) {
      var line = lines[i];
      var fileMatch = line.match(/^## `([^`]+)`/);
      var overviewMatch = line.match(/^## Overview/);

      if (fileMatch || overviewMatch) {
        if (currentLines.length > 0) {
          sections.push({ heading: currentHeading, lines: currentLines });
        }
        currentHeading = fileMatch ? fileMatch[1] : '__overview__';
        currentLines = [];
      } else {
        currentLines.push(line);
      }
    }
    if (currentLines.length > 0) {
      sections.push({ heading: currentHeading, lines: currentLines });
    }

    // Process each section
    for (var s = 0; s < sections.length; s++) {
      var section = sections[s];

      // Overview node
      if (section.heading === '__overview__') {
        var overviewText = cleanBuffer(section.lines);
        if (overviewText.length > 50) {
          nodes.push({ content: 'Project Overview\n' + overviewText });
        }
        continue;
      }

      // File section — split into summary part and function parts
      var filePath = section.heading;
      var fileLines = section.lines;
      var summaryBuffer = [];
      var functions = [];
      var currentFn = null;
      var dependsOn = [];

      for (var j = 0; j < fileLines.length; j++) {
        var fline = fileLines[j];
        var fnMatch = fline.match(/^#### `([^`]+)`(.*)/);
        var impMatch = fline.match(/^\*\*Imports from:\*\*\s*(.+)/);

        if (fnMatch) {
          // Flush current function
          if (currentFn) {
            functions.push(currentFn);
          }
          currentFn = { name: fnMatch[1], meta: fnMatch[2] || '', lines: [] };
        } else if (currentFn) {
          currentFn.lines.push(fline);
        } else if (impMatch) {
          // Capture REAL dependency edges from DocGen's deterministic import analysis, and
          // keep this structural line OUT of the summary text so its words don't pollute
          // keywords. These become file→file graph edges at build time (maps the codebase).
          var refs = impMatch[1].match(/`([^`]+)`/g) || [];
          for (var r = 0; r < refs.length; r++) dependsOn.push(refs[r].replace(/`/g, ''));
        } else if (/^\*\*(Imported by|Uses globals|Referenced by):\*\*/.test(fline)) {
          // Reverse/global structural lines — excluded from keyword content; the forward
          // "Imports from" edges already capture graph direction (reverse is implied).
        } else {
          // Before any #### — this is file summary content
          summaryBuffer.push(fline);
        }
      }
      if (currentFn) functions.push(currentFn);

      // Create file summary node — carries filePath + its dependencies for edge wiring.
      var summaryText = cleanBuffer(summaryBuffer);
      if (summaryText.length > 30) {
        nodes.push({ content: filePath + '\n' + summaryText, filePath: filePath, dependsOn: dependsOn });
      }

      // Create function nodes (each tagged with full file path)
      for (var f = 0; f < functions.length; f++) {
        var fn = functions[f];
        var fnContent = cleanBuffer(fn.lines);
        if (fnContent.length > 20) {
          nodes.push({ content: filePath + ' ' + fn.name + '\n' + fnContent, filePath: filePath });
        }
      }
    }

    return nodes;
  }

  /**
   * Clean a buffer of lines — remove HTML tags, empty lines at start/end, collapse whitespace.
   */
  function cleanBuffer(lines) {
    var out = [];
    var inCode = false;
    for (var i = 0; i < lines.length; i++) {
      var l = lines[i];
      // Drop fenced code blocks entirely — the <details>Source</details> dumps are pure
      // syntax/variable-name noise that swamp the keyword profile with non-topic tokens.
      if (/^\s*```/.test(l)) { inCode = !inCode; continue; }
      if (inCode) continue;
      // Drop HTML wrappers, separators, and structural scaffolding lines.
      if (l === '---') continue;
      if (/^<\/?details>?/.test(l)) continue;
      if (/^<summary>/.test(l)) continue;
      if (/^<a id=/.test(l)) continue;
      if (/^\s*\*\*\d+\s*lines?\*\*\s*\|/i.test(l)) continue;                                   // "**638 lines** | 4 functions/classes"
      if (/^\s*#{2,4}\s+(Exports|Dependencies|Functions\s*&\s*Methods)\s*$/i.test(l)) continue; // structural headers
      out.push(l);
    }
    // Strip markdown emphasis/heading/backtick punctuation so keywords come from words,
    // not syntax; then collapse whitespace.
    return out.join('\n')
      .replace(/[`*#>]/g, ' ')
      .replace(/[ \t]+/g, ' ')
      .replace(/\n{3,}/g, '\n\n')
      .trim();
  }

  /**
   * Build a minimal memory state JSON from an array of nodes.
   */
  function buildStateFromNodes(nodes) {
    // Build the nodes THROUGH the library's Chain so keyword extraction, graph init,
    // ids/parenting, and token counts all come from one place (src/core/chain.js) —
    // not a demo-side copy that can silently drift from the library (see
    // agents/library-boundary.md). LiminalMemory.Chain is the exported library class.
    var chain = new LiminalMemory.Chain();
    var fileToNodeId = {}; // filePath → its summary node id (first node created per file)
    var built = [];
    for (var i = 0; i < nodes.length; i++) {
      var created = chain.append('system', nodes[i].content);
      built.push({ id: created.id, src: nodes[i] });
      if (nodes[i].filePath && !fileToNodeId[nodes[i].filePath]) {
        fileToNodeId[nodes[i].filePath] = created.id;
      }
    }

    // Deterministic dependency edges: each file → the files it imports from. This maps the
    // real codebase wiring into the graph with zero LLM, so clusters form around actual
    // modules (and edges here can trigger structural splits at ingest — that's intended).
    var depEdges = 0;
    for (var b = 0; b < built.length; b++) {
      var deps = built[b].src.dependsOn;
      if (!deps || !deps.length) continue;
      for (var d = 0; d < deps.length; d++) {
        var toId = fileToNodeId[deps[d]];
        if (toId && toId !== built[b].id) { chain.link(built[b].id, toId); depEdges++; }
      }
    }
    console.log('[Ingest] Built ' + chain.length + ' nodes, wired ' + depEdges + ' dependency edges');

    return { chain: chain.export() };
  }

  return { init: init };
})();
